# -*- coding: utf-8 -*-
"""Despliegue_AtaqueAlCorazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wo2Dc3FksHzXbO8yNjMgHfhkYoST0sDO

#Despliegue

-cargar modelo

-cargar datos futuros

-preparar datos futuros

-aplicar el modeolo
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle
filename = 'modelo-class.pkl'

# Cargar el contenido del archivo pickle en una sola variable para inspección
#loaded_content = pickle.load(open(filename, 'rb'))
modelo, encoder, variables, scaler = pickle.load(open(filename, 'rb'))

print(type(loaded_content))

print(loaded_content)

#Cargamos los datos futuros
data = pd.read_excel("ataque_corazon.xlsx")
data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos
#STREAMLIT SOLO SE EJECUTA EN UN SERVIDOR WEB

import streamlit as st

st.title('Predicción de Ataque al corazon')

age = st.slider('Edad', min_value=0, max_value=100, value=30, step=1)
hypertension = st.selectbox('Hipertensión', ['Yes', 'No'])
heart_disease = st.selectbox('Enfermedad Cardíaca', ['Yes', 'No'])
ever_married = st.selectbox('¿Alguna vez casado?', ['Yes', 'No'])
avg_glucose_level = st.number_input('Nivel de glucosa', value=80.0)
smoking_status = st.selectbox('Estado de fumador', ['formerly smoked', 'never smoked', 'smokes', 'Unknown'])


#Dataframe
data = pd.DataFrame([{
    'age': age,
    'hypertension': hypertension,
    'heart_disease': heart_disease,
    'ever_married': ever_married,
    'avg_glucose_level': avg_glucose_level,
    'smoking_status': smoking_status
}])
#datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]
#data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False

data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status'], drop_first=False, dtype=int)
data_preparada = pd.get_dummies(data_preparada, columns=['hypertension','heart_disease','ever_married',], drop_first=True, dtype=int)
data_preparada.head()

from numpy._core.fromnumeric import var
#Se adicionan las columnas faltantes
#variables=['age', 'hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level', 'smoking_status', 'stroke_ataque_corazon']
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""#**Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 12%")